language: python
python:
    - 2.7
    - pypy2.7-5.8.0
    - 3.4
    - 3.5
    - 3.6
    - nightly
    - pypy3.5-5.8.0
branches:
    only:
        - master
        - develop
install:
    - pip install -e .
script:
    - pytest
